######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 21 14:10:29 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
include(opencv.pro)

# Input
HEADERS += CameraStream.h CamWidget.h
#FORMS += mainwindow.ui
SOURCES += CameraStream.cpp CamWidget.cpp main.cpp
